# Project: Super Alien Box
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"S:/Dev/MinGW64/lib" -L"S:/Dev/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"S:/SFML/lib" -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system
INCS     = -I"S:/Dev/MinGW64/include" -I"S:/Dev/MinGW64/x86_64-w64-mingw32/include" -I"S:/Dev/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"S:/SFML/include"
CXXINCS  = -I"S:/Dev/MinGW64/include" -I"S:/Dev/MinGW64/x86_64-w64-mingw32/include" -I"S:/Dev/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"S:/Dev/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"S:/SFML/include"
BIN      = "Super Alien Box.exe"
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
